services:
  # Contao frontend module "calendar_event_booking_member_list"
  Markocupic\CalendarEventBookingBundle\Controller\FrontendModule\CalendarEventBookingMemberListController:
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    arguments:
    - '@database_connection'
    tags:
    - { name: contao.frontend_module, category: events, type: calendar_event_booking_member_list }
    - { name: container.service_subscriber }
    public: true

  # Contao frontend module "eventbooking"
  Markocupic\CalendarEventBookingBundle\Controller\FrontendModule\CalendarEventBookingController:
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: events, type: eventbooking }
    - { name: container.service_subscriber }
    public: true

    # Contao frontend module "unsubscribefromevent"
  Markocupic\CalendarEventBookingBundle\Controller\FrontendModule\UnsubscribeFromEventController:
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    arguments:
    - '@Markocupic\CalendarEventBookingBundle\Notification\NotificationHelper'
    tags:
    - { name: contao.frontend_module, category: events, type: unsubscribefromevent }
    - { name: container.service_subscriber }
    public: true

  # Contao dca class tl_module
  Markocupic\CalendarEventBookingBundle\Contao\Dca\TlModule:
    arguments:
    - '@contao.framework'
    public: true

  # Notification helper class
  Markocupic\CalendarEventBookingBundle\Notification\NotificationHelper:
    arguments:
    - '@contao.framework'
    public: true

