services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Markocupic\CalendarEventBookingBundle\:
        resource: ../../
        exclude: ../../{Event,Model,DependencyInjection,Resources}
