markocupic_calendar_event_booking:
    checkout_manager_factory: default
    checkout:
        default:
            steps:
                subscription:
                    step: 'Markocupic\CalendarEventBookingBundle\Checkout\Step\SubscriptionStep'
                    template: '@Contao_MarkocupicCalendarEventBookingBundle/checkout_step_subscription.html.twig'
                    priority: 100
                finalisation:
                    step: 'Markocupic\CalendarEventBookingBundle\Checkout\Step\FinalisationStep'
                    template: '@Contao_MarkocupicCalendarEventBookingBundle/checkout_step_finalisation.html.twig'
                    priority: 90
